### ISSUE TITLE
Try to load dialogs , Exception Invalid constructor code C7AC6496

### ISSUE THREAD

**Issue by TheBottleGit** [steavy29/Telegram.Net#11]
```
class ContactData
    {
        public readonly int UserID;
        public readonly long AccessHash;
        public readonly string UserName;
        public ContactData(int UserID, long AccessHash, string UserName)
        {
            this.UserID = UserID;
            this.AccessHash = AccessHash;
            this.UserName = UserName;
        }
        public override string ToString()
        {
            return this.UserName;
        }
    }
```
 
```
private async Task load_Dialogs()
        {
            var AllDialog = await Authenticated.GetDialogs(0, 30, 0) as MessagesDialogsConstructor;
            var DialogsUsersList = AllDialog.users;
            lst_Dialogs.Items.Clear();

            foreach (User X in DialogsUsersList)
            {
                try
                {
                    var userReq = X as UserRequestConstructor;
                    if (userReq != null)
                    {
                        lst_Dialogs.Items.Add(
                            new Helper.ContactData(userReq.id, userReq.accessHash,
                            userReq.firstName + " " + userReq.lastName));
                    }
                    else
                    {
                        var userContact = X as UserContactConstructor;
                        if (userContact != null)
                        {
                            lst_Dialogs.Items.Add(
                                new Helper.ContactData(userContact.id, userContact.accessHash,
                                userContact.firstName + " " + userContact.lastName));
                        }
                        else
                        {
                            var userForeign = X as UserForeignConstructor;
                            if (userForeign != null) lst_Dialogs.Items.Add(
                                new Helper.ContactData(userForeign.id, userForeign.accessHash,
                                userForeign.firstName + " " + userForeign.lastName));

                            else
                            {
                                var UserSelf = X as UserSelfConstructor;
                                if (UserSelf != null) lst_Dialogs.Items.Add(
                                new Helper.ContactData(UserSelf.id, 0,
                                UserSelf.firstName + " " + UserSelf.lastName));
                            }
                        }
                    }
                }
                catch (Exception ex) { MessageBox.Show(ex.ToString()); }
            }
        }
```
Code
Session dat = http://rgho.st/8MfqSvz9s (Can't attach)
//Напиши в вк если остались вопросы(Rus text to author)

**Comment by steavy29** [comment]
Fixed. Let me know if it worked for you. And thanks for the report.

**Comment by TheBottleGit** [comment]
No, not fixed it.
Project : http://rgho.st/7KNcVmwkB
session.dat inside

**Comment by steavy29** [comment]
Made additional fixes. Check out now, please.

**Comment by TheBottleGit** [comment]
Latest version, Invalid constructor code E26F42F1

**Comment by steavy29** [comment]
Hm, strange. I tried `GetDialogs` with you `session.dat` and it works. Did you pull this latest commit 51910e2 ?

**Comment by TheBottleGit** [comment]
I try get Dialogs, not contacts

**Comment by TheBottleGit** [comment]
Yes, i did pull. Null exception
![screenshot_1](https://cloud.githubusercontent.com/assets/13104180/19680318/05ed96c2-9ac7-11e6-90cd-4b898190addf.png)

**Comment by steavy29** [comment]
`as MessagesDialogsConstructors`
There are two possible return types for `GetDialogs`: `MessagesDialogsConstructors` and **`MessagesDialogsSliceConstructor`**

**Comment by TheBottleGit** [comment]
Fixed
